global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

- job_name: prometheus
  metrics_path: /metrics
  static_configs:
  - targets: ['localhost:9090']

- job_name: products
  metrics_path: /metrics
  static_configs:
  - targets: ['products:8001']

- job_name: orders
  metrics_path: /metrics
  static_configs:
  - targets: ['orders:8002']

- job_name: reviews
  metrics_path: /metrics
  static_configs:
  - targets: ['reviews:8003']